
customer:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass123!
    driver-class-name: org.postgresql.Driver
  allow-get-accounts: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'